In [24]:
import numpy as np

In [27]:
# Create Array From List 

# 1 D Array 
arr1 = np.array([1,2,3,4,5,])
arr2 = np.array([5,6,7,"Venom",9])
print(arr1 ," " , type(arr1) ," " , arr1.shape )
print(arr2 ," " , type(arr2) ," " , arr2.shape )
print()

# 2 D Array 
arr3 = np.array([[6,7,8,9],[2,3,4,5],[4,5,6,7]])
print(arr3 ," " , type(arr3) ," " , arr3.shape )



[1 2 3 4 5]   <class 'numpy.ndarray'>   (5,)
['5' '6' '7' 'Venom' '9']   <class 'numpy.ndarray'>   (5,)

[[6 7 8 9]
 [2 3 4 5]
 [4 5 6 7]]   <class 'numpy.ndarray'>   (3, 4)


In [59]:
# Create Array From in built Funtion 

arr4 = np.zeros((3,3))   # prefill
print(arr4 , arr4.shape)
print()
arr5 = np.ones((3,4))   # prefill with ones
print(arr5 , arr5.shape)
print()
arr6 = np.full((3,2),9)  # prefill with specific value
print(arr6 , arr6.shape)
print()
arr7 = np.eye(4)  # identity matrix
print(arr7 , arr7.shape)
print()
arr8 = np.arange(0,100,18)  # elements in range 
print(arr8 , arr8.shape)
print()
arr9 = np.linspace(1,100,3)  # evenly spaced element
print(arr9 , arr9.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)

[[9 9]
 [9 9]
 [9 9]] (3, 2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)

[ 0 18 36 54 72 90] (6,)

[  1.   50.5 100. ] (3,)
