Array Properties -

In [7]:
import numpy as np
arr = np.array([[1,2,3],[5,6,7],[8,9,0]])

print("Dimesion    : " , arr.shape)  # Dimension m X n
print("Total Elements  : " ,arr.size)   # Total Elements m*n
print("n Dimension : " ,arr.ndim)   # n Dimension
print("Data Type   : " ,arr.dtype)  # Data Type

Dimesion    :  (3, 3)
Total Elements  :  9
n Dimension :  2
Data Type   :  int64


In [9]:
# TpyeCasting of Arrays 's Elements 

#Method 01 
float_arr = np.array(arr,dtype = "float64")
print(float_arr , float_arr.dtype)

#Method 02
float_arr2 = arr.astype(np.float64)
print(float_arr2 , float_arr2.dtype)


[[1. 2. 3.]
 [5. 6. 7.]
 [8. 9. 0.]] float64
[[1. 2. 3.]
 [5. 6. 7.]
 [8. 9. 0.]] float64
