Operation on Array 

In [4]:
# Reshaping

import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr , arr.shape)
print()

reshaped = arr.reshape((3,2))
print(reshaped , reshaped.shape)
print()

flattened = arr.flatten()
print(flattened , flattened.shape)
print()

[[1 2 3]
 [4 5 6]] (2, 3)

[[1 2]
 [3 4]
 [5 6]] (3, 2)

[1 2 3 4 5 6] (6,)



In [6]:
# Accessing via Indexing

arr2 = np.array([0,1,2,3,4,5,6,7])
print(arr2[0] , " ",arr2[7])
arr3 = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr3[0][1] , arr3[2][2])

0   7
1 8


In [13]:
# Fancy Indexing
arr4 = np.array([0,12,23,34,45,56,67,78])
idx = [0,3,7]
print(arr4[idx])
print()
# Boolean Indexing
arr5 = np.array([0,12,23,34,45,56,67,78])
print(arr5[arr5>50])
print(arr5[arr5%2==0])
print(arr5[arr5%2!=0])

[ 0 34 78]

[56 67 78]
[ 0 12 34 56 78]
[23 45 67]


In [18]:
# Slicing - Similar to List
arr6 = np.array([0,12,23,34,45,56,67,78])

print(arr6[1:5])  # start : end : step
print(arr6[:6]) 
print(arr6[3:]) 
print(arr6[:]) 
print(arr6[::2]) 

[12 23 34 45]
[ 0 12 23 34 45 56]
[34 45 56 67 78]
[ 0 12 23 34 45 56 67 78]
[ 0 23 45 67]
