In [10]:
# copy vs view
import numpy as np 

# List - Copy 
num = [0,1,2,3,4,5,6]
sub_list = num[1:4]
print(sub_list)
sub_list[0] = 99
print(sub_list, "  ", num)
print()

# Numpy Array - View
arr = np.array([0,1,2,3,4,5,6])
sub_arr = arr[1:4] # Basically sub_arr also pointing to the part of original arr
print(sub_arr)
sub_arr[0] = 69
print(sub_arr, "  ",arr)
print()

# but if we want to make actual copy then :
arr2 = np.array([0,1,2,3,4,5,6])
sub_arr2 = arr2[1:4].copy()
print(sub_arr2)
sub_arr2[0] = 100
print(sub_arr2, "  ",arr2)

[1, 2, 3]
[99, 2, 3]    [0, 1, 2, 3, 4, 5, 6]

[1 2 3]
[69  2  3]    [ 0 69  2  3  4  5  6]

[1 2 3]
[100   2   3]    [0 1 2 3 4 5 6]
