Axes in Multiple Arrays

In [12]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(np.sum(arr))
print()

sum_column = np.sum(arr , axis =0)
sum_row = np.sum(arr , axis =1)

print(sum_column)
print()
print(sum_row)
print()

# Slicing on axes
sliced_arr = np.array(arr[0:2,1:2])
print(sliced_arr)




[[1 2 3]
 [4 5 6]
 [7 8 9]]
45

[12 15 18]

[ 6 15 24]

[[2]
 [5]]


In [27]:
arr3D = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(arr3D , arr3D.shape)
print()

# Indexing 
print(arr3D[0,2,1] , arr3D[1,1,0])
print()

# Slicing
print(" First Row and Colums from both Layers  : ")
print(arr3D[: , 0 ,:])  # first row from both layers
print(arr3D[: , : ,0])  # first column from both layers
print()

# Updation using slicing
arr3D[: , 0 ,:] = 999  # Replace view with 999
print(" 3D Array After Updation : ")
print(arr3D , arr3D.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)

6 9

 First Row and Colums from both Layers  : 
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]

 3D Array After Updation : 
[[[999 999]
  [  3   4]
  [  5   6]]

 [[999 999]
  [  9  10]
  [ 11  12]]] (2, 3, 2)
