Vectorization and Broadcasting

In [3]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

#Vectorization
print(arr**3)
print(arr+10)

[  1   8  27  64 125 216]
[11 12 13 14 15 16]


In [ ]:
# Broadcasting

arr2 = np.array([[1,2,3],[4,5,6],[8,9,0]]) # (3,3) -> (1,3)
arr3 = np.array([4,5,6])
print(arr2 + arr3)

[[ 5  7  9]
 [ 8 10 12]
 [12 14  6]]


In [10]:
# Normalization
arr4 = np.array([[1,2],[3,4]])
mean = np.mean(arr4)
std_dev = np.std(arr4)

normalized_arr = ((arr4-mean)/std_dev)
print(normalized_arr)
print(mean , std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5 1.118033988749895
