Mathematical Funtions

In [2]:
import numpy as np
# aggregation
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmax(arr))
print(np.argmin(arr))

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))

15
120
5
1
4
0
3.0
1.4142135623730951
3.0
2.0


In [3]:
# power fxn
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr , 3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [4]:
arr = np.array([1,2,3,4,5,10,16])

# log fxns
print(np.log(arr))
print(np.log2(arr))
print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 2.30258509
 2.77258872]
[0.         1.         1.5849625  2.         2.32192809 3.32192809
 4.        ]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 2.20264658e+04 8.88611052e+06]


In [5]:
# rounding fxns

print(np.round(3.14739))
print(np.ceil(3.14739))
print(np.floor(3.14739))
print(np.trunc(3.14739))
print(np.round(3.14739))


3.0
4.0
3.0
3.0
3.0


In [ ]:
arr = np.array([1, 2, -5, 3, 8, -4, 2, 5])
print(np.abs(arr))     # [1 2 5 3 8 4 2 5]
print(np.sort(arr))    # [-5 -4  1  2  2  3  5  8]
print(np.unique(arr))  # [-5 -4  1  2  3  5  8]

[1 2 5 3 8 4 2 5]
[-5 -4  1  2  2  3  5  8]
[-5 -4  1  2  3  5  8]
